<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="AcurusResume" duration-ms="396" started-at="2020-12-07T10:11:33Z" finished-at="2020-12-07T10:11:34Z">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.runScenario(io.cucumber.testng.PickleWrapper, io.cucumber.testng.FeatureWrapper)[pri:0, instance:Runner.RunnerClass@1f32542]" name="runScenario" class="io.cucumber.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test name="ResumeTrackerCucumber" duration-ms="396" started-at="2020-12-07T10:11:33Z" finished-at="2020-12-07T10:11:34Z">
      <class name="Runner.RunnerClass">
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:Runner.RunnerClass@1f32542]" name="setUpClass" is-config="true" duration-ms="231" started-at="2020-12-07T10:11:33Z" finished-at="2020-12-07T10:11:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="FAIL" signature="runScenario(io.cucumber.testng.PickleWrapper, io.cucumber.testng.FeatureWrapper)[pri:0, instance:Runner.RunnerClass@1f32542]" name="runScenario" duration-ms="6" started-at="2020-12-07T10:11:34Z" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2020-12-07T10:11:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA["Login Data"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Check Login Functionality"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AbstractMethodError">
            <full-stacktrace>
              <![CDATA[java.lang.AbstractMethodError
at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:73)
at org.testng.internal.Invoker.runTestListeners(Invoker.java:1389)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:559)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AbstractMethodError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method status="PASS" signature="tearDownClass()[pri:0, instance:Runner.RunnerClass@1f32542]" name="tearDownClass" is-config="true" duration-ms="12" started-at="2020-12-07T10:11:34Z" finished-at="2020-12-07T10:11:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- Runner.RunnerClass -->
    </test> <!-- ResumeTrackerCucumber -->
  </suite> <!-- AcurusResume -->
</testng-results>
